import './globals.css'
import { Inter } from 'next/font/google'
import Sidebar from './components/sidebar/sidebar';
import msg from '../public/msgIcon.svg';
import Image from 'next/image';
import Notify from '../public/notify.svg';
import Settings from '../public/settings.svg';
const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <div className="navbar">
<div className="navbar-left">
        AVALON</div>
      <div className="navbar-right">
        <input className="search-bar" type="text" placeholder="search" />
        <div className="icon-main-wrapper"> 
        <Image src={Notify}/>
  <Image  src={msg} />
  <Image src={Settings}/>
  </div>
      </div>
        {children}
        </div>
        <div className="main-wrapper">
        <div className="sidebar-uikit"><Sidebar/></div>
        </div>
        </body>
    </html>
  )
}
